CREATE TABLE employees
        (EMPLOYEE_ID NUMBER(6) NOT NULL,
        FIRST_NAME VARCHAR2(20) NOT NULL,
        LAST_NAME VARCHAR2(25),
        EMAIL VARCHAR2(25),
        PHONE_NUMBER VARCHAR2(20) NOT NULL,
        HIRE_DATE DATE,
        JOB_ID VARCHAR2(10),
        SALARY NUMBER(8,2) NOT NULL,
        COMMISSION_PCT NUMBER(2,2) NOT NULL,
        MANAGER_ID NUMBER(6) NOT NULL,
        DEPARTMENT_ID NUMBER(4) NOT NULL
        );
