CREATE TABLE employees
        (EMPLOYEE_ID NUMBER(6),
        FIRST_NAME VARCHAR2(20),
        LAST_NAME VARCHAR2(25),
        EMAIL VARCHAR2(25),
        PHONE_NUMBER VARCHAR2(20),
        HIRE_DATE DATE,
        JOB_ID VARCHAR2(10),
        SALARY NUMBER(8,2),
        COMMISSION_PCT NUMBER(2,2),
        MANAGER_ID NUMBER(6),
        DEPARTMENT_ID NUMBER(4)
        );
